### ISSUE TITLE
Feature: `attr_key` to change attribute prepended identifier

### ISSUE THREAD

**Issue by Redsandro** [damirn/rapidx2j#13]
Currently, all attributes are prepended with `@`. This is hardcoded at [parser.cc:74](https://github.com/damirn/rapidx2j/blob/master/src/parser.cc#L74).

`@` is an inconvenient character because it's not allowed in dot notation:

```
<xml>
<some attribute="test"></some>
</xml>
```

`xml.some.@attribute` is not allowed. We need to write:
`xml.some[@attribute]`

It would be convenient to be able to customize this prepended string using `options.attr_key`. E.g.:
- `@` // This is not allowed in dot notation, but some people like it
- `_` // This is allowed in dot notation
- `attr_` // This is also allowed in dot notation
- ` `// Nothing!`xml2json` doesn't prepend attributes. Just overwrite/skip the tags.

**Comment by NFNChris** [comment]
This is also resolved in my pull request via the attr_prefix option

**Comment by Redsandro** [comment]
This is a very welcome feature, and together with your other fix, I might reconsider using rapidx2j again since I can simply replace the parse logic and the output will be the same but with a speed bonus. :+1:

**Comment by NFNChris** [comment]
This can be closed
