### ISSUE TITLE
Feature: Have attributes collected in single subobject.

### ISSUE THREAD

**Issue by Redsandro** [damirn/rapidx2j#14]
In order to be a **swap-in replacement for slower popular parsers** out there, it would be cool to **optionally** have all attributes collected in a single sub-object, e.g. using `options.collect_attrs`. This object can have the name set by [`attr_key`](https://github.com/damirn/rapidx2j/issues/13) (or less versatile: hardcoded to `@`).

E.g.:

```
<xml>
   <some attrib="test">
        <crazy>
            value
        </crazy>
   </some>
</xml>
```

```
{
    some: {
        '@': {
                attrib: 'test'
        },
        crazy: 'value'
    }
}
```

The only problem is when the key with attributes also holds a non-tag value:

```
<xml>
   <some attrib="test">
        value
   </some>
</xml>
```

**xml2json**'s solution is that in this case, and only in this case, the value will be in a key named `$t`:

```
{
    some: {
        attrib: 'test'
        '$t': 'value'
    }
}
```

**node-expat** does the same, but names the key `#`:

```
{
    some: {
        '@': {
                attrib: 'test'
        },
        '#': 'value'
    }
}
```

---

If we have this tag key depend on an option, e.g. `collect_tags` we can mimic all the other parsers, allowing users to easily use `rapidx2j` as snap-in faster replacement.

```
var options = {
    attr_key : '@',
    tag_key : '#',
    collect_tags : true, // defaults to false
    collect_attrs : true // defaults to false
};
```

If the key with attributes also holds a non-tag value and `collect_tags` is `false`, it should be set to `true` only for the current tag.

The option to set it to `true` is necessary for when you can't predict if the `xml` you are receiving has an attribute on a key that you want to reference no matter what. So you know you can always `some['#']` whether or not `some` has attributes.

**Comment by Redsandro** [comment]
@damirn I didn't know before you wanted to be able follow [the `JXON` spec](https://developer.mozilla.org/en-US/docs/JXON). The discussed feature will allow you to do that:

```
<xml>
   <some attrib="test">
        <crazy>
            value
        </crazy>
   </some>
</xml>
```

```
var options = {
    attr_key : 'keyAttributes',
    tag_key : 'keyValue',
    collect_tags : false,
    collect_attrs : true
};
```

```
{
    some: {
        keyAttributes: {
                attrib: 'test'
        },
        keyValue: 'value'
    }
}
```

**Comment by damirn** [comment]
To be honest, I'm not trying to follow the spec, I'm only implementing the algorithm from the link above. Also, I'm not quite following your example, is this some kind of a transformation of output?

**Comment by Redsandro** [comment]
Basically, it gathers all attributes in an 'attribute' object in stead of mixing them in with the tags.
This fixes the case where a tag can have an attribute and a child-tag with the same name, while keeping the exact tag/attribute names.

For example, this allows you to insert XML as BSON into MongoDB and keep it searchable and reversible using the exact same variable names.

**Comment by NFNChris** [comment]
I understand the desire to aggregate attributes - and to have the flexibility to specify under what key this aggregation occurs.  But I'm not entirely clear on the need for what you are calling 'collect_tags' - can you clarify?

I guess what I'm imagining is that the following xml:

`<xml>
   <some attrib="test">
        <crazy>
            value
        </crazy>
   </some>
</xml>`

Is transformed with these options parameters:

`var options = {
    attribute_prefix : '_',
    aggregate_attributes: true   
};`

To produce the following JSON / object:

`{
    some: {
      '_': {
        attrib: 'test'
      },
      'crazy': 'value'
    }
  }`

Why do we need to aggregate the child tags separately?

**Comment by Redsandro** [comment]
> I guess what I'm imagining is that the following xml:  
> `<xml> <some attrib="test"> <crazy> value </crazy> </some> </xml>`  
> Is transformed with these options parameters:  
> `var options = { attribute_prefix : '_', aggregate_attributes: true };`  

First of all, that would be awesome.

As for the child tags, I'm not sure what I was thinking at the time. I think everything is accounted for, if you can specify the `tag_prefix` so it won't collide with a tag and fits with preference.

`var options = { attribute_prefix : '_attr', tag_prefix: '_val', aggregate_attributes: true, preserve_case: true};`

``` xml
<parent myAttr1="someVal" myAttr2="otherVal">
    croozy
</parent>
```

``` json
{
    "parent": {
        "_attr": {
            "myAttr1": "someVal",
            "myAttr2": "otherVal"
        },
        "_val": "croozy"
    }
}
```

---

``` xml
<parent myAttr1="someVal" myAttr2="otherVal">
    croozy
    <child>crazy</child>
</parent>
```

``` json
{
    "parent": {
        "_attr": {
            "myAttr1": "someVal",
            "myAttr2": "otherVal"
        },
        "_val": "croozy",
        "child": "crazy"
    }
}
```

---

``` xml
<parent myAttr1="someVal" myAttr2="otherVal">
    <child>crazy 1</child>
    <child>crazy 2</child>
    <child>crazy 3</child>
</parent>
```

``` json
{
    "parent": {
        "_attr": {
            "myAttr1": "someVal",
            "myAttr2": "otherVal"
        },
        "child": ["crazy 1", "crazy 2", "crazy 3"]
    }
}
```

**Comment by Redsandro** [comment]
Any updates on attribute collection?

**Comment by NFNChris** [comment]
This is now resolved in the pull request I initiated today.  If it's accepted and merged, we can close this issue / feature request.

Sorry for the delay! Finally needed this in my own project.

**Comment by Redsandro** [comment]
Interesting. When it's accepted, I'll be benchmarking. :smile:

**Comment by NFNChris** [comment]
I would be very surprised if this impacted performance at all

**Comment by NFNChris** [comment]
This can be closed

**Comment by NFNChris** [comment]
Can we push an update to npm for these changes?
