### ISSUE TITLE
Remove toLower() calls on tags and properties.

### ISSUE THREAD

**Issue by Redsandro** [damirn/rapidx2j#16]
[XML is a case-sensitive format](http://xml.silmaril.ie/case.html). So are js objects. Removing the casing is not a good practice and should not be a default.

Can we just remove those two `toLower()` calls on attributes and tags, or are they being used?

If they are being used, I propose we introduce a boolean option that defaults to false.

**Comment by damirn** [comment]
I used algorithms from https://developer.mozilla.org/en-US/docs/JXON and I will stick to them, so removing toLower() is not an option and it will also break backward compatibility

**Comment by Redsandro** [comment]
Ah, I didn't know. Makes sense. I will add an option then, otherwise we cannot use this for the popular `json` format in stead of `jxon`.

I will do it after you look at this PR https://github.com/damirn/rapidx2j/issues/15 otherwise I have to deal with merge conflicts.

**Comment by NFNChris** [comment]
This can now be achieved via the preserve_case option

**Comment by damirn** [comment]
Closing since 'preserve_case' is implemented now.

**Comment by Redsandro** [comment]
Nice. :+1: 

This puts `rapidx2j` back on my radar. There are still features missing for a viable replacement for slower modules, namely:
- Collecting all attributes in single object: https://github.com/damirn/rapidx2j/issues/14
- Have empty attribute something other than `null`: https://github.com/damirn/rapidx2j/issues/12

The first one #14 is the most important one, and I couldn't figure out how to do it myself, otherwise I could have forked this.

I had a PR for that last one (https://github.com/damirn/rapidx2j/pull/15) but there was no merge and no feedback on the PR or other issues for a while. I dropped the idea of moving to `rapidx2j` because the slower modules have more active development.
