### ISSUE TITLE
Does not compile with Node.js 5.8.0

### ISSUE THREAD

**Issue by Redsandro** [damirn/rapidx2j#17]
Does this support Node.js 4.x and 5.x?

**Comment by damirn** [comment]
it should work with node 4.4.0:

git clone https://github.com/damirn/rapidx2j.git

npm install rapidx2j/

I just tried it on mac os x w/o issues

**Comment by NFNChris** [comment]
For anyone else wrestling with this, I had to upgrade to gcc-4.7 and g++-4.7 before this would compile successfully.

**Comment by damirn** [comment]
Closed as outdated.
