### ISSUE TITLE
Doesn't work with buffer

### ISSUE THREAD

**Issue by Redsandro** [damirn/rapidx2j#21]
Feed it a number and it will say 

> 'XML needs to be a string of buffer.'

Feed it a buffer and it will say

> Wrong argument; expected String
>    at Object.exports.parse (rapidx2j/index.js:64:17)

**Comment by damirn** [comment]
I fixed the obvious typo. Can you share a small test case please?

**Comment by Redsandro** [comment]
To be expected:
```js
rapidx2j.parse(42)
// XML needs to be a string of buffer.
```

Does not work:
```js
var fs = require('fs')
var buffer = fs.readFileSync('test.xml')
rapidx2j.parse(buffer)
// Wrong argument; expected String
```

Works:
```js
var fs = require('fs')
var buffer = fs.readFileSync('test.xml')
var string = buffer.toString()
rapidx2j.parse(string)
```

**Comment by damirn** [comment]
Can you please try the latest code from the master branch?
