### ISSUE TITLE
NSP Vulnerability

### ISSUE THREAD

**Issue by jruts** [damirn/rapidx2j#23]
Hi, 

I am using this library in a project and after running a [nsp check](https://nodesecurity.io) a [vulnerability](https://nodesecurity.io/advisories/57) was discovered. Could you look into fixing this?

**Comment by damirn** [comment]
Hi,

is this the correct URL https://nodesecurity.io/advisories/57 ?

**Comment by jruts** [comment]
@damirn, yes it is. But I was investigating some more and I don't think you can do anything about it.
The full path is `tc-fs-provider-atcom@1.0.0 > rapidx2j@0.1.0 > cmake-js@3.4.1 > tar@1.0.3  `.

So the issue is the outdated version of `tar`. But you already depend on the latest version of `cmake-js`, so they need to update it.
The later version of `tar` (>=2.0.0) fixes the vulnerability. 

The only thing you could do is use [node-gyp](https://www.npmjs.com/package/node-gyp) instead of [cmake-js](https://www.npmjs.com/package/cmake-js).

They are doing the same thing, but `gyp` is created by google and is a lot more popular regarding the stats on npm.

**Comment by damirn** [comment]
I only used cmake while I was developing rapidx2j, since I like CLion; for normal builds / npm installs, node-gyp is used. Can I close this one then?

**Comment by jruts** [comment]
@damirn of course you can. Just wanted to inform you :)

**Comment by damirn** [comment]
closing as per https://github.com/damirn/rapidx2j/issues/23#issuecomment-304251428
