### ISSUE TITLE
Create always arrays, like it can be done with other xml parsers

### ISSUE THREAD

**Issue by arnaud-soulard** [damirn/rapidx2j#28]
I would like to use rapidx2j with an option that enable array mode, to have always array, even if there is only one element per array.

"fast-xml-parser" call it "arrayMode"
"xml2js" call it "explicitArray"

**Comment by arnaud-soulard** [comment]
I made some modifications in parser.cc that seem to work.
It would be great to review those changes and maybe integrate them in the official version?

[parser.cc.txt](https://github.com/damirn/rapidx2j/files/1394775/parser.cc.txt)

**Comment by damirn** [comment]
creating a PR is the preferred way to send updates/changes etc. thanks.

**Comment by arnaud-soulard** [comment]
So, I guess I have to create a branch, push it, then I will be able to open a PR?
Firstly I wanted to open a PR, but since I was missing some steps, I opened an issue.

**Comment by damirn** [comment]
yes, that is correct

**Comment by arnaud-soulard** [comment]
I just created a PR, maybe we could close this issue.

**Comment by palash3** [comment]
Is this task complete ?
