### ISSUE TITLE
Ignore attrs

### ISSUE THREAD

**Issue by akaNightmare** [damirn/rapidx2j#32]
I would like to use rapidx2j with an option that ignores all attributes.

"fast-xml-parser" call it "ignoreAttributes"
"xml2js" call it "ignoreAttrs"

Thanks.

**Comment by damirn** [comment]
Thanks for the suggestion. Can you add a test case please?

**Comment by akaNightmare** [comment]
@damirn 
```js
parse('<x><a attr1="a" attr2="b">val</a></x>', { ignore_attr: true });
```

Expected value
```json
{ "x": { "a": "val" } }
```
Attributes `attr1` and `attr2` are complytelly ignored.
