### ISSUE TITLE
rapidxml_print.hpp is missing

### ISSUE THREAD

**Issue by kasutajaimin** [damirn/rapidx2j#39]
A rather unexpected omission from a RapidXML wrapper.
Or is there somewhere a rapid**j2x** i've missed?

Regards

**Comment by damirn** [comment]
rapidxml_print.hpp is no where referenced in the project. Are you getting an error during the build?

**Comment by kasutajaimin** [comment]
No error, but a puzzling surprise to find the only rapidxml wrapper for node (to my knowledge) to actually only provide half of it. How would one go about extracting a part of the xml, a rather common operation, a la original rapidxml or php's simplexml? Regexing the xml or manual reassembly, kind of devaluing the performance advantage of rapidxml, appear the only options, or have i missed something?

**Comment by damirn** [comment]
well, this module is not just a wrapper for rapidxml, but it's actually an XML to JSON transformer. in other words, there's no point in 'extracting a part of the xml' as you put it; your original XML will be represented by a JSON object.

**Comment by kasutajaimin** [comment]
So how to revert a node from the object back to a non-destructive xml string representation with maximum performance and without any 3rd packages? As already stated identifying and extracting sub-nodes from xml as xml is a very common industry practice.
Or do you have any knowledge of an actual rapidxml wrapper that's eluded me thus far?

**Comment by damirn** [comment]
i have no idea, but clearly, this module cannot be used for that purpose, nor it was designed with such requirement. you will have to look somewhere else.
