### ISSUE TITLE
`parse_int_numbers` seems to do exactly the same as `parse_float_numbers`

### ISSUE THREAD

**Issue by Redsandro** [damirn/rapidx2j#9]
``` javascript
var r = require('../build/Release/rapidx2j'),
    x = '<x><a>3.14159</a><b>123</b><c>0</c><d>1.00</d></x>';

var o = r.parse(x);
console.log(o);

o = r.parse(x, { parse_float_numbers: false });
console.log(o);

o = r.parse(x, { parse_int_numbers: false });
console.log(o);
```

```
{ a: 3.14159, b: 123, c: 0, d: 1 }
{ a: '3.14159', b: '123', c: '0', d: '1.00' }
{ a: '3.14159', b: '123', c: '0', d: '1.00' }
```

**Comment by Redsandro** [comment]
Perhaps ambiguous int and float parse options should be one single option:
`parse_numbers`.

**Comment by damirn** [comment]
This is also regression, test's output should read:

{ a: 3.14159, b: 123, c: 0, d: 1 }
{ a: '3.14159', b: 123, c: 0, d: '1.00' }
{ a: 3.14159, b: 123, c: 0, d: 1 }

**Comment by Redsandro** [comment]
Just so I understand correctly; `parse_float_numbers` overrides `parse_int_numbers` because both set to `true` yields the same results as `parse_int_numbers` set to `false`?
